# Generated by Django 4.0.3 on 2022-08-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInput', models.TextField()),
                ('intentClassified', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
